### ISSUE TITLE
 Fatal error: Call to undefined function JiraRestApi\curl_init() 

### ISSUE THREAD

**Issue by srinisubra** [rgies/agile-dashboard#1]
Hi There,
             I am new to PHP and would like to try your project agile-dashboard. As mentioned in your readme, i have installed php, mysql and composer. 

I started the PHP server as shown below. 

C:\jiraagilemeasure\agile-dashboard>php -S localhost:8000

I made a modification in index.php line # 13 and removed / to correctly indentify the web/app_dev.php

After setting up the https JIRA url - with username/pswd i get the following error

**CRITICAL - Fatal error: Call to undefined function JiraRestApi\curl_init() 
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Fatal error: Call to undefined function JiraRestApi\curl_init()" at C:\jiraagilemeasure\agile-dashboard\vendor\lesstif\php-jira-rest-client\src\JiraClient.php line 168** 

The full stack trace

Logs   - 2 errors
INFO - Matched route "jira_core_widget_login_create". 
DEBUG - The Symfony\Component\Form\Extension\Csrf\CsrfProvider\CsrfProviderAdapter class is deprecated since version 2.4 and will be removed in version 3.0. Use the Symfony\Component\Security\Csrf\CsrfTokenManager class instead. 
DEBUG - Read existing security token from the session. 
DEBUG - SELECT t0.id AS id_1, t0.username AS username_2, t0.password AS password_3, t0.lastname AS lastname_4, t0.firstname AS firstname_5, t0.role AS role_6, t0.jobtitle AS jobtitle_7, t0.email AS email_8, t0.is_active AS is_active_9, t0.modified AS modified_10, t0.created AS created_11, t0.domain AS domain_12, t0.last_login_date AS last_login_date_13 FROM User t0 WHERE t0.id = ? 
DEBUG - User was reloaded from a user provider. 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest". 
DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". 
DEBUG - SELECT t0.id AS id_1, t0.provider AS provider_2, t0.value AS value_3, t0.updated AS updated_4, t0.created AS created_5, t0.domain AS domain_6, t0.connected AS connected_7 FROM Credential t0 WHERE t0.provider = ? AND t0.domain = ? 
INFO - Function mcrypt_get_iv_size() is deprecated 
INFO - Function mcrypt_create_iv() is deprecated 
INFO - Function mcrypt_decrypt() is deprecated 
DEBUG - RGies\JiraCoreWidgetBundle\Form\LoginType: The FormTypeInterface::setDefaultOptions() method is deprecated since version 2.7 and will be removed in 3.0. Use configureOptions() instead. This method will be added to the FormTypeInterface with Symfony 3.0. 
INFO - Function mcrypt_get_iv_size() is deprecated 
INFO - Function mcrypt_create_iv() is deprecated 
INFO - Function mcrypt_encrypt() is deprecated 
DEBUG - SELECT t0.id AS id_1, t0.provider AS provider_2, t0.value AS value_3, t0.updated AS updated_4, t0.created AS created_5, t0.domain AS domain_6, t0.connected AS connected_7 FROM Credential t0 WHERE t0.provider = ? AND t0.domain = ? 
DEBUG - "START TRANSACTION" 
DEBUG - UPDATE Credential SET updated = ? WHERE id = ? 
DEBUG - "COMMIT" 
DEBUG - SELECT t0.id AS id_1, t0.provider AS provider_2, t0.value AS value_3, t0.updated AS updated_4, t0.created AS created_5, t0.domain AS domain_6, t0.connected AS connected_7 FROM Credential t0 WHERE t0.provider = ? AND t0.domain = ? 
INFO - Function mcrypt_get_iv_size() is deprecated 
INFO - Function mcrypt_create_iv() is deprecated 
INFO - Function mcrypt_decrypt() is deprecated 
CRITICAL - Fatal error: Call to undefined function JiraRestApi\curl_init() 
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Fatal error: Call to undefined function JiraRestApi\curl_init()" at C:\jiraagilemeasure\agile-dashboard\vendor\lesstif\php-jira-rest-client\src\JiraClient.php line 168 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest". 
DEBUG - Using "filename" as the default strategy is deprecated since version 1.27. Use "name" instead. 
DEBUG - The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead. 
DEBUG - The Symfony\Component\Security\Core\SecurityContextInterface interface is deprecated since version 2.6 and will be removed in 3.0. 
DEBUG - Referencing the "core" extension by its name (defined by getName()) is deprecated since 1.26 and will be removed in Twig 2.0. Use the Fully Qualified Extension Class Name instead. 
DEBUG - Referencing the "core" extension by its name (defined by getName()) is deprecated since 1.26 and will be removed in Twig 2.0. Use the Fully Qualified Extension Class Name instead. 
DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". 
DEBUG - Defining the initRuntime() method in the "form" extension is deprecated since version 1.23. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended).

**Comment by Stereck** [comment]
The dashboard is calling APIs via curl. Therefore the PHP curl module need to be installed.
e.g:
$ sudo apt-get install php5-curl
$ sudo /etc/init.d/apache2 restart

**Comment by srinisubra** [comment]
Awesome. It is working
